modLoader = "javafml" # mandatory
loaderVersion = "${loader_version_range}" # mandatory
license = "${mod_license}"
issueTrackerURL="https://github.com/SomeDom/Taboo/issues" #optional
displayURL="https://github.com/SomeDom/Taboo" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
#logoFile="taboo.png" #optional
#credits="" #optional
#[[mixins]]
#config="${mod_id}.mixins.json"
#[features."${mod_id}"]
#openGLVersion="[3.2,)"

[[mods]] # mandatory
modId = "${mod_id}" # mandatory
version = "${mod_version}" # mandatory
displayName = "${mod_name}" # mandatory
authors = "${mod_authors}" # optional
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "smartbrainlib"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}" # mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="taboo.mixins.json"